# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a7146438bfc41cf980281ba5484b9792c5487051450d3189ac129e945989420897faad4bcea61883aca5cb450979b8f5db31a068378f888867104e01b3b8917

test:
  secret_key_base: 5ee112660a07e4cf2ec99cbfe8ebaa65ea7574fb03162cc00a6c6345bf8d8793bcb77429a91faeeeccd735ab36d06d94712d047e2a1fb7baf5dd508bc3377def

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
